package org.moyrax.reporting;

/**
 * Contains the basic information of a report generated by a {@link Reporter}.
 *
 * @author Matias Mirabelli &lt;lumen.night@gmail&gt;
 * @since 1.2.2
 */
public abstract class ReportInfo {
  /**
   * The report's name.
   */
  private String name;

  /**
   * Returns the report's name. The report name will be used to generate
   * meaningful output from the {@link Reporter}s.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets this report's name.
   *
   * @param aName Report name. It cannot be null or empty.
   */
  public void setName(final String aName) {
    this.name = aName;
  }
}
